title: Avaleht
columns:
  left:
    width: 2/3
    sections:
      content:
        type: fields
        fields:    
          text:
            label: Tekst
            type: blocks
            fieldsets:
              - heading
              - text
              - list
              - line
              - quote
              - image
              - gallery
              - video
              - code
              - markdown  
              - customhtml            
            help: Klahv Enter alustab järgmist lõiku (uue ja eelmise lõigu vahele jääb vahe). Shift+Enter liigub lihtsalt järgmisele reale (jääb väiksem vahe kui lõikude vahele).  
          home_photos:
            label: Avalehe fotod
            type: files
            layout: cards
            template: image
            info: "{{ file.dimensions }}"
            image:
              ratio: 9/6
              cover: true
            size: small                
  right:
    width: 1/3
    sections:
      content2:
        type: fields
        fields:                     
          meta_description:
            label: Meta-kirjeldus
            type: textarea
            size: medium
            help: Lühikene kirjeldus veebilehe sisust, mida kuvatakse Google otsingutulemustes. Peab andma väga lühidalt ülevaate, millest veebilehel juttu, sisaldama üleskutset veebilehte külastama, fookusmärksõnu ja võimalusel ka sisumärksõnu. Max 165 tähemärki.
          meta_tags:
            label: Tags
            type: tags            
          line:
            type: line              
      files:
        type: files
        headline: Üleslaetud pildid / failid