columns:
  left:
    width: 2/3
    sections:
      drafts:
        headline: Mustandid
        type: pages
        status: draft
      unlisted:
        headline: Peidetud sisu
        type: pages
        status: unlisted   
      published:
        headline: Avaldatud sisu
        type: pages
        status: listed
        help: Järjestamine drag-n-drop meetodil. Siin nähtavad avaldatud leheküljed kajastuvad menüüs.
      content:
        type: fields
        fields:  
          line-c:
            type: line 
          sponsors:
            label: Sponsorid
            type: files   
          footer:
            label: Jaluses olev tekst
            type: blocks            
  right:
    width: 1/3
    sections:
      content2:
        type: fields
        fields:           
          logo:
            label: Kodulehekülje logo
            type: files  
            max: 1             
          line-a:
            type: line  
          google_analytics:
            label: Google Analytics kood
            type: textarea
            size: medium
          facebook:
            label: Facebooki link
            type: text   
          instagram:
            label: Instagrami link
            type: text             
          line-b:
            type: line              
      files:
        type: files
        headline: Üleslaetud pildid / failid     