# Each page blueprint must have a title, the title may be different from the file name
title:
  ee: Liikmed
  ru: Члены
# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 📖

# Define the form layout with two columns
# More about columns: https://getkirby.com/docs/guide/blueprints/layout#defining-columns

columns:
  - width: 1/3
    # In the first column, we reuse the `notes` section
    # (defined in `/site/blueprints/sections/notes.yml` twice with different page status and headline
    sections:
      drafts:
        extends: sections/members
        label:
          ee: Mustandid
          ru: Черновики
        status: draft

      unlisted:
        extends: sections/members
        label:
          ee: Kontrollitakse
          ru: Проверяется
        status: unlisted

  - width: 2/3
    # In the second column, we reuse the same section, this time for listed pages and with a different headline
    sections:
      listed:
        extends: sections/members
        label:
          ee: Kinnitatud
          ru: Опубликовано
        status: listed
        size: small
        layout: cards
options:
  delete:
    user: false
  changeStatus:
    user: false
  changeTitle:
    user: false
  changeSlug:
    user: false
  sort:
    user: false
  settings:
    user: false
# More about pages sections: https://getkirby.com/docs/reference/panel/sections/pages